# ラベルの定義
labels:
  - name: 'bug'
    color: 'B60205'
  - name: 'Priority: high'
    color: 'D93F0B'
  - name: ':memo: 設計'
    color: '5319E7'
  - name: ':test_tube: QA'
    color: '5319E7'
  - name: ':policeman: SRE'
    color: '5319E7'
  - name: ':up: SystemUpdate'
    color: '5319E7'
  - name: ':closed_lock_with_key: Security'
    color: '5319E7'

  - name: '新技術獲得'
    color: '0E8A16'
  - name: '負債返済'
    color: '0052CC'
  - name: 'technical goal'
    color: 'B60205'
  - name: '技術調査'
    color: 'FBCA04'
  - name: '事例調査'
    color: 'D93F0B'

  - name: ':memo: 記事'
    color: '32CA7E'

# 展開対象のリポジトリと設定するラベル
repos:
  - name: daikin-tic/ADS-dev-env-template
    labels:
      - 'Priority: high'
      - ':memo: 設計'
      - ':test_tube: QA'
      - ':policeman: SRE'
      - ':up: SystemUpdate'
      - ':closed_lock_with_key: Security'
      - '新技術獲得'
      - '負債返済'
      - 'technical goal'
      - '技術調査'
      - '事例調査'
      - ':memo: 記事'
