changelog:
  exclude:
    # リリースノートから除外したいユーザー
    authors:
      - github-actions
      - dependabot
  categories:
    - title: 🐛 バグ修正
      labels:
        - 'bug'
    - title: 👍 UX/UI 改善
      labels:
        - 'dependencies'
    - title: 👍 技術的改善
      labels:
        - 'documentation'
    - title: ♻️ その他変更
      labels:
        - '*'
