printWidth: 100
tabWidth: 2
singleQuote: true
trailingComma: 'es5'
semi: false
endOfLine: 'lf'
# cdkなど最大文字数が大きい方が見やすいようなファイルは下記のようにディレクトリを指定してoverridesすることができる
# overrides:
#   - files: ['backend/**/*.ts', 'frontend/cdk/**/*.ts']
#     options:
#       printWidth: 150
