name: vitestでapiテスト(stepci)を実行

on:
  pull_request:
    branches:
      - main
      - dev
      - feature/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}(${{ github.head_ref}})
  cancel-in-progress: true

jobs:
  api-vitest:
    name: api vitest
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-1
      ACCOUNT_ID: ${{ vars.AWS_SUNABA_ACCOUNT_ID }}
    defaults:
      run:
        working-directory: test/stepci
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.jsのバージョン指定
        uses: actions/setup-node@v4
        with:
          node-version: 16.15

      - name: npm ci
        run: |
          npm ci

      - name: workflow.ymlを作成
        run: |
          npx stepci generate ../../docs/api/openapi.yml workflow.yml

      # AWSリソースにアクセス
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_SUNABA_ACCOUNT_ID }}:role/github-oidc-role
          role-session-name: GitHubActions-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Token取得
        id: id-token
        run: |
          auth=$(aws cognito-idp admin-initiate-auth --user-pool-id ${{vars.USER_POOL_ID}} --client-id ${{vars.CLIENT_ID}} --auth-flow "ADMIN_USER_PASSWORD_AUTH" --auth-parameters USERNAME=${{vars.TEST_USER_NAME}},PASSWORD=${{secrets.TANIO_USER_PASSWORD}} --query "AuthenticationResult.IdToken")
          echo "ID_TOKEN=$auth" >> $GITHUB_OUTPUT

      - name: Authorizationを追加
        run: |
          step_length=$(yq '.tests.default.steps | length' workflow.yml)
          echo $step_length
          cnt=0
          while [ "$cnt" -lt "$step_length" ]; do
            yq -i '.tests.default.steps[$cnt].http.headers.Authorization=${{ steps.id-token.outputs.ID_TOKEN }}' workflow.yml
            cnt=`expr $cnt + 1`
          done

      - name: API Test
        run: |
          npx stepci run
