name: 'Pull Requestの自動生成'

on:
  push:
    branches:
      - dev

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ADS_APP_ID }}
          private-key: ${{ secrets.ADS_ACCESSTOKEN_PRIVATESECRET }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Reset promotion branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          branch: dev
          base: main
          title: ':rocket: Mainマージ'
          body: |
            DevからMainへの自動生成されたPull Requestです
            validationを確認してから承認してください
