name: Automatically labeling and renaming pull request.

on:
  pull_request:
    types: [opened]

jobs:
  auto-labeling-pr:
    runs-on: ubuntu-latest

    env:
      # PATを作成してリポジトリに配置（許可する項目はISSUE参照）
      GH_TOKEN: ${{ secrets.LABELING_PULL_REQUEST }}

    steps:
      - uses: actions/checkout@v4

      # ブランチ名からISSUE番号とプルリクのタイトルを取得する（先頭の数字をISSUE番号としている）
      # 想定：feature/1234-issueTitle, hotfix/1234-issueTitle, 1234-issueTitle etc.
      - name: Get issue number and title name
        id: issue_num
        run: |
          issue_title=$(echo ${{github.head_ref}} | cut -d "/" -f2)
          if [ $issue_title == '' ]; then
            issue_title=${{github.head_ref}}
          fi
          issue_num=$(echo $issue_title | sed -e 's/^\([0-9]*\)[^0-9]*[^ ]*/\1/g')
          title_name=$(echo "[$issue_title](https://github.com/daikin-tic/${{github.event.repository.name}}/issues/$issue_num)")
          pull_request_num=$(echo $GITHUB_REF | sed -e 's/[^0-9]//g')
          echo "issue_num=$issue_num" >> $GITHUB_OUTPUT
          echo "title_name=$title_name" >> $GITHUB_OUTPUT
          echo "pull_request_num=$pull_request_num" >> $GITHUB_OUTPUT

      # PRのタイトルを変更する
      - name: Renaming pull request
        if: ${{ steps.issue_num.outputs.issue_num }}
        run: |
          gh pr edit ${{ steps.issue_num.outputs.pull_request_num }} --title '${{ steps.issue_num.outputs.title_name }}'

      # ISSUEのラベルを追加する
      - name: Auto labeling by issue label
        if: ${{ steps.issue_num.outputs.issue_num }}
        run: |
          labels=$(gh api -H "Accept: application/vnd.github+json" -H "Authorization: token $GH_TOKEN" /repos/daikin-tic/${{github.event.repository.name}}/issues/${{ steps.issue_num.outputs.issue_num }}/labels)
          while read label_name; do
            gh pr edit ${{ steps.issue_num.outputs.pull_request_num }} --add-label "$label_name"
          done < <(echo $labels | jq '.[].name')
